using System;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Windows.Forms;
using QuanLyYTe.Services;

namespace QuanLyYTe.Forms.Coordinator
{
    partial class frmCoordinator
    {
    	protected override void Dispose(bool disposing)
    	{
    		if (disposing && components != null)
    		{
    			components.Dispose();
    		}
    		base.Dispose(disposing);
    	}
    
    	private void InitializeComponent()
    	{
    		this.tabCoordinator = new System.Windows.Forms.TabControl();
    		this.tabPatients = new System.Windows.Forms.TabPage();
    		this.splitContainer1 = new System.Windows.Forms.SplitContainer();
    		this.dgvPatients = new System.Windows.Forms.DataGridView();
    		this.panel1 = new System.Windows.Forms.Panel();
    		this.btnRefreshPatient = new System.Windows.Forms.Button();
    		this.btnSearchPatient = new System.Windows.Forms.Button();
    		this.txtSearchPatient = new System.Windows.Forms.TextBox();
    		this.lblSearch = new System.Windows.Forms.Label();
    		this.grpPatientDetails = new System.Windows.Forms.GroupBox();
    		this.btnPatientClear = new System.Windows.Forms.Button();
    		this.btnPatientUpdate = new System.Windows.Forms.Button();
    		this.btnPatientAdd = new System.Windows.Forms.Button();
    		this.txtPatientUsernameDb = new System.Windows.Forms.TextBox();
    		this.lblPatientUsernameDb = new System.Windows.Forms.Label();
    		this.txtPatientDrugAllergies = new System.Windows.Forms.TextBox();
    		this.lblPatientDrugAllergies = new System.Windows.Forms.Label();
    		this.txtPatientFamilyMedicalHistory = new System.Windows.Forms.TextBox();
    		this.lblPatientFamilyMedicalHistory = new System.Windows.Forms.Label();
    		this.txtPatientMedicalHistory = new System.Windows.Forms.TextBox();
    		this.lblPatientMedicalHistory = new System.Windows.Forms.Label();
    		this.txtPatientCityProvince = new System.Windows.Forms.TextBox();
    		this.lblPatientCityProvince = new System.Windows.Forms.Label();
    		this.txtPatientDistrict = new System.Windows.Forms.TextBox();
    		this.lblPatientDistrict = new System.Windows.Forms.Label();
    		this.txtPatientStreet = new System.Windows.Forms.TextBox();
    		this.lblPatientStreet = new System.Windows.Forms.Label();
    		this.txtPatientHouseNo = new System.Windows.Forms.TextBox();
    		this.lblPatientHouseNo = new System.Windows.Forms.Label();
    		this.txtPatientIdCard = new System.Windows.Forms.TextBox();
    		this.lblPatientIdCard = new System.Windows.Forms.Label();
    		this.txtPatientBirthDate = new System.Windows.Forms.TextBox();
    		this.lblPatientBirthDate = new System.Windows.Forms.Label();
    		this.txtPatientGender = new System.Windows.Forms.TextBox();
    		this.lblPatientGender = new System.Windows.Forms.Label();
    		this.txtPatientFullName = new System.Windows.Forms.TextBox();
    		this.lblPatientFullName = new System.Windows.Forms.Label();
    		this.txtPatientId = new System.Windows.Forms.TextBox();
    		this.lblPatientId = new System.Windows.Forms.Label();
    		this.tabCreateMR = new System.Windows.Forms.TabPage();
    		this.grpCreateMR = new System.Windows.Forms.GroupBox();
    		this.btnMRCreate = new System.Windows.Forms.Button();
    		this.label5 = new System.Windows.Forms.Label();
    		this.txtMRServiceResult = new System.Windows.Forms.TextBox();
    		this.lblMRServiceResult = new System.Windows.Forms.Label();
    		this.txtMRConclusion = new System.Windows.Forms.TextBox();
    		this.lblMRConclusion = new System.Windows.Forms.Label();
    		this.txtMRTreatmentPlan = new System.Windows.Forms.TextBox();
    		this.lblMRTreatmentPlan = new System.Windows.Forms.Label();
    		this.txtMRDiagnosis = new System.Windows.Forms.TextBox();
    		this.lblMRDiagnosis = new System.Windows.Forms.Label();
    		this.lblSectionSpecialty = new System.Windows.Forms.Label();
    		this.cmbMRDoctorId = new System.Windows.Forms.ComboBox();
    		this.lblMRDoctorId = new System.Windows.Forms.Label();
    		this.cmbMRDeptId = new System.Windows.Forms.ComboBox();
    		this.lblMRDeptId = new System.Windows.Forms.Label();
    		this.lblSectionDoctor = new System.Windows.Forms.Label();
    		this.dtpMRRecordDate = new System.Windows.Forms.DateTimePicker();
    		this.lblMRRecordDate = new System.Windows.Forms.Label();
    		this.cmbMRPatientId = new System.Windows.Forms.ComboBox();
    		this.lblMRPatientId = new System.Windows.Forms.Label();
    		this.txtMRRecordId = new System.Windows.Forms.TextBox();
    		this.lblMRRecordId = new System.Windows.Forms.Label();
    		this.lblSectionInfo = new System.Windows.Forms.Label();
    		this.tabAssignDoctor = new System.Windows.Forms.TabPage();
    		this.splitContainer2 = new System.Windows.Forms.SplitContainer();
    		this.dgvMedicalRecords = new System.Windows.Forms.DataGridView();
    		this.groupBox1 = new System.Windows.Forms.GroupBox();
    		this.btnUpdateAssignDoctor = new System.Windows.Forms.Button();
    		this.cmbAssignDoctor = new System.Windows.Forms.ComboBox();
    		this.label9 = new System.Windows.Forms.Label();
    		this.cmbAssignDept = new System.Windows.Forms.ComboBox();
    		this.label10 = new System.Windows.Forms.Label();
    		this.txtAssignMRDate = new System.Windows.Forms.TextBox();
    		this.label8 = new System.Windows.Forms.Label();
    		this.txtAssignMRPatient = new System.Windows.Forms.TextBox();
    		this.label7 = new System.Windows.Forms.Label();
    		this.txtAssignMRId = new System.Windows.Forms.TextBox();
    		this.label6 = new System.Windows.Forms.Label();
    		this.tabAssignTech = new System.Windows.Forms.TabPage();
    		this.splitContainer3 = new System.Windows.Forms.SplitContainer();
    		this.dgvServiceRecords = new System.Windows.Forms.DataGridView();
    		this.lblTechNotice = new System.Windows.Forms.Label();
    		this.groupBox2 = new System.Windows.Forms.GroupBox();
    		this.btnUpdateAssignTech = new System.Windows.Forms.Button();
    		this.cmbAssignTech = new System.Windows.Forms.ComboBox();
    		this.label15 = new System.Windows.Forms.Label();
    		this.txtAssignSRDate = new System.Windows.Forms.TextBox();
    		this.label13 = new System.Windows.Forms.Label();
    		this.txtAssignSRType = new System.Windows.Forms.TextBox();
    		this.label12 = new System.Windows.Forms.Label();
    		this.txtAssignSRId = new System.Windows.Forms.TextBox();
    		this.label11 = new System.Windows.Forms.Label();
    		this.tabProfile = new System.Windows.Forms.TabPage();
    		this.groupBox3 = new System.Windows.Forms.GroupBox();
    		this.btnUpdateProfile = new System.Windows.Forms.Button();
    		this.txtSelfHometown = new System.Windows.Forms.TextBox();
    		this.label20 = new System.Windows.Forms.Label();
    		this.txtSelfPhone = new System.Windows.Forms.TextBox();
    		this.label21 = new System.Windows.Forms.Label();
    		this.txtSelfSpecialty = new System.Windows.Forms.TextBox();
    		this.label18 = new System.Windows.Forms.Label();
    		this.txtSelfRole = new System.Windows.Forms.TextBox();
    		this.label19 = new System.Windows.Forms.Label();
    		this.txtSelfFullName = new System.Windows.Forms.TextBox();
    		this.label17 = new System.Windows.Forms.Label();
    		this.txtSelfStaffId = new System.Windows.Forms.TextBox();
    		this.label16 = new System.Windows.Forms.Label();
    		this.lblTitle = new System.Windows.Forms.Label();
    		this.tabCoordinator.SuspendLayout();
    		this.tabPatients.SuspendLayout();
    		((System.ComponentModel.ISupportInitialize)this.splitContainer1).BeginInit();
    		this.splitContainer1.Panel1.SuspendLayout();
    		this.splitContainer1.Panel2.SuspendLayout();
    		this.splitContainer1.SuspendLayout();
    		((System.ComponentModel.ISupportInitialize)this.dgvPatients).BeginInit();
    		this.panel1.SuspendLayout();
    		this.grpPatientDetails.SuspendLayout();
    		this.tabCreateMR.SuspendLayout();
    		this.grpCreateMR.SuspendLayout();
    		this.tabAssignDoctor.SuspendLayout();
    		((System.ComponentModel.ISupportInitialize)this.splitContainer2).BeginInit();
    		this.splitContainer2.Panel1.SuspendLayout();
    		this.splitContainer2.Panel2.SuspendLayout();
    		this.splitContainer2.SuspendLayout();
    		((System.ComponentModel.ISupportInitialize)this.dgvMedicalRecords).BeginInit();
    		this.groupBox1.SuspendLayout();
    		this.tabAssignTech.SuspendLayout();
    		((System.ComponentModel.ISupportInitialize)this.splitContainer3).BeginInit();
    		this.splitContainer3.Panel1.SuspendLayout();
    		this.splitContainer3.Panel2.SuspendLayout();
    		this.splitContainer3.SuspendLayout();
    		((System.ComponentModel.ISupportInitialize)this.dgvServiceRecords).BeginInit();
    		this.groupBox2.SuspendLayout();
    		this.tabProfile.SuspendLayout();
    		this.groupBox3.SuspendLayout();
    		base.SuspendLayout();
    		this.tabCoordinator.Controls.Add(this.tabPatients);
    		this.tabCoordinator.Controls.Add(this.tabCreateMR);
    		this.tabCoordinator.Controls.Add(this.tabAssignDoctor);
    		this.tabCoordinator.Controls.Add(this.tabAssignTech);
    		this.tabCoordinator.Controls.Add(this.tabProfile);
    		this.tabCoordinator.Dock = System.Windows.Forms.DockStyle.Fill;
    		this.tabCoordinator.Font = new System.Drawing.Font("Segoe UI", 10f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
    		this.tabCoordinator.Location = new System.Drawing.Point(0, 50);
    		this.tabCoordinator.Name = "tabCoordinator";
    		this.tabCoordinator.SelectedIndex = 0;
    		this.tabCoordinator.Size = new System.Drawing.Size(1200, 750);
    		this.tabCoordinator.TabIndex = 1;
    		this.tabCoordinator.SelectedIndexChanged += new System.EventHandler(tabCoordinator_SelectedIndexChanged);
    		this.tabPatients.Controls.Add(this.splitContainer1);
    		this.tabPatients.Location = new System.Drawing.Point(4, 32);
    		this.tabPatients.Name = "tabPatients";
    		this.tabPatients.Padding = new System.Windows.Forms.Padding(3);
    		this.tabPatients.Size = new System.Drawing.Size(1192, 714);
    		this.tabPatients.TabIndex = 0;
    		this.tabPatients.Text = "Quản lý Bệnh nhân";
    		this.tabPatients.UseVisualStyleBackColor = true;
    		this.splitContainer1.Dock = System.Windows.Forms.DockStyle.Fill;
    		this.splitContainer1.FixedPanel = System.Windows.Forms.FixedPanel.Panel2;
    		this.splitContainer1.Location = new System.Drawing.Point(3, 3);
    		this.splitContainer1.Name = "splitContainer1";
    		this.splitContainer1.Panel1.Controls.Add(this.dgvPatients);
    		this.splitContainer1.Panel1.Controls.Add(this.panel1);
    		this.splitContainer1.Panel2.Controls.Add(this.grpPatientDetails);
    		this.splitContainer1.Size = new System.Drawing.Size(1186, 708);
    		this.splitContainer1.SplitterDistance = 750;
    		this.splitContainer1.TabIndex = 0;
    		this.dgvPatients.AllowUserToAddRows = false;
    		this.dgvPatients.AllowUserToDeleteRows = false;
    		this.dgvPatients.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
    		this.dgvPatients.BackgroundColor = System.Drawing.Color.White;
    		this.dgvPatients.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
    		this.dgvPatients.Dock = System.Windows.Forms.DockStyle.Fill;
    		this.dgvPatients.EnableHeadersVisualStyles = false;
    		this.dgvPatients.Location = new System.Drawing.Point(0, 60);
    		this.dgvPatients.Name = "dgvPatients";
    		this.dgvPatients.ReadOnly = true;
    		this.dgvPatients.RowHeadersWidth = 51;
    		this.dgvPatients.RowTemplate.Height = 29;
    		this.dgvPatients.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
    		this.dgvPatients.Size = new System.Drawing.Size(750, 648);
    		this.dgvPatients.TabIndex = 1;
    		this.dgvPatients.CellClick += new System.Windows.Forms.DataGridViewCellEventHandler(dgvPatients_CellClick);
    		this.panel1.BackColor = System.Drawing.Color.White;
    		this.panel1.Controls.Add(this.btnRefreshPatient);
    		this.panel1.Controls.Add(this.btnSearchPatient);
    		this.panel1.Controls.Add(this.txtSearchPatient);
    		this.panel1.Controls.Add(this.lblSearch);
    		this.panel1.Dock = System.Windows.Forms.DockStyle.Top;
    		this.panel1.Location = new System.Drawing.Point(0, 0);
    		this.panel1.Name = "panel1";
    		this.panel1.Size = new System.Drawing.Size(750, 60);
    		this.panel1.TabIndex = 0;
    		this.btnRefreshPatient.BackColor = System.Drawing.Color.FromArgb(236, 239, 241);
    		this.btnRefreshPatient.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
    		this.btnRefreshPatient.ForeColor = System.Drawing.Color.FromArgb(38, 50, 56);
    		this.btnRefreshPatient.Location = new System.Drawing.Point(520, 15);
    		this.btnRefreshPatient.Name = "btnRefreshPatient";
    		this.btnRefreshPatient.Size = new System.Drawing.Size(100, 30);
    		this.btnRefreshPatient.TabIndex = 7;
    		this.btnRefreshPatient.Text = "Làm mới";
    		this.btnRefreshPatient.UseVisualStyleBackColor = false;
    		this.btnRefreshPatient.Click += new System.EventHandler(btnRefreshPatient_Click);
    		this.btnSearchPatient.BackColor = System.Drawing.Color.FromArgb(25, 118, 210);
    		this.btnSearchPatient.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
    		this.btnSearchPatient.ForeColor = System.Drawing.Color.White;
    		this.btnSearchPatient.Location = new System.Drawing.Point(410, 15);
    		this.btnSearchPatient.Name = "btnSearchPatient";
    		this.btnSearchPatient.Size = new System.Drawing.Size(100, 30);
    		this.btnSearchPatient.TabIndex = 6;
    		this.btnSearchPatient.Text = "Tìm kiếm";
    		this.btnSearchPatient.UseVisualStyleBackColor = false;
    		this.btnSearchPatient.Click += new System.EventHandler(btnSearchPatient_Click);
    		this.txtSearchPatient.Location = new System.Drawing.Point(120, 15);
    		this.txtSearchPatient.Name = "txtSearchPatient";
    		this.txtSearchPatient.PlaceholderText = "Nhập Mã, CCCD hoặc Họ tên...";
    		this.txtSearchPatient.Size = new System.Drawing.Size(280, 30);
    		this.txtSearchPatient.TabIndex = 1;
    		this.lblSearch.AutoSize = true;
    		this.lblSearch.Location = new System.Drawing.Point(10, 18);
    		this.lblSearch.Name = "lblSearch";
    		this.lblSearch.Size = new System.Drawing.Size(83, 23);
    		this.lblSearch.TabIndex = 0;
    		this.lblSearch.Text = "Tra cứu:";
    		this.grpPatientDetails.BackColor = System.Drawing.Color.White;
    		this.grpPatientDetails.Controls.Add(this.btnPatientClear);
    		this.grpPatientDetails.Controls.Add(this.btnPatientUpdate);
    		this.grpPatientDetails.Controls.Add(this.btnPatientAdd);
    		this.grpPatientDetails.Controls.Add(this.txtPatientUsernameDb);
    		this.grpPatientDetails.Controls.Add(this.lblPatientUsernameDb);
    		this.grpPatientDetails.Controls.Add(this.txtPatientDrugAllergies);
    		this.grpPatientDetails.Controls.Add(this.lblPatientDrugAllergies);
    		this.grpPatientDetails.Controls.Add(this.txtPatientFamilyMedicalHistory);
    		this.grpPatientDetails.Controls.Add(this.lblPatientFamilyMedicalHistory);
    		this.grpPatientDetails.Controls.Add(this.txtPatientMedicalHistory);
    		this.grpPatientDetails.Controls.Add(this.lblPatientMedicalHistory);
    		this.grpPatientDetails.Controls.Add(this.txtPatientCityProvince);
    		this.grpPatientDetails.Controls.Add(this.lblPatientCityProvince);
    		this.grpPatientDetails.Controls.Add(this.txtPatientDistrict);
    		this.grpPatientDetails.Controls.Add(this.lblPatientDistrict);
    		this.grpPatientDetails.Controls.Add(this.txtPatientStreet);
    		this.grpPatientDetails.Controls.Add(this.lblPatientStreet);
    		this.grpPatientDetails.Controls.Add(this.txtPatientHouseNo);
    		this.grpPatientDetails.Controls.Add(this.lblPatientHouseNo);
    		this.grpPatientDetails.Controls.Add(this.txtPatientIdCard);
    		this.grpPatientDetails.Controls.Add(this.lblPatientIdCard);
    		this.grpPatientDetails.Controls.Add(this.txtPatientBirthDate);
    		this.grpPatientDetails.Controls.Add(this.lblPatientBirthDate);
    		this.grpPatientDetails.Controls.Add(this.txtPatientGender);
    		this.grpPatientDetails.Controls.Add(this.lblPatientGender);
    		this.grpPatientDetails.Controls.Add(this.txtPatientFullName);
    		this.grpPatientDetails.Controls.Add(this.lblPatientFullName);
    		this.grpPatientDetails.Controls.Add(this.txtPatientId);
    		this.grpPatientDetails.Controls.Add(this.lblPatientId);
    		this.grpPatientDetails.Dock = System.Windows.Forms.DockStyle.Fill;
    		this.grpPatientDetails.ForeColor = System.Drawing.Color.FromArgb(25, 118, 210);
    		this.grpPatientDetails.Location = new System.Drawing.Point(0, 0);
    		this.grpPatientDetails.Name = "grpPatientDetails";
    		this.grpPatientDetails.Size = new System.Drawing.Size(432, 708);
    		this.grpPatientDetails.TabIndex = 1;
    		this.grpPatientDetails.TabStop = false;
    		this.grpPatientDetails.Text = "Chi tiết bệnh nhân";
    		this.btnPatientClear.BackColor = System.Drawing.Color.FromArgb(236, 239, 241);
    		this.btnPatientClear.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
    		this.btnPatientClear.ForeColor = System.Drawing.Color.FromArgb(38, 50, 56);
    		this.btnPatientClear.Location = new System.Drawing.Point(280, 560);
    		this.btnPatientClear.Name = "btnPatientClear";
    		this.btnPatientClear.Size = new System.Drawing.Size(100, 35);
    		this.btnPatientClear.TabIndex = 27;
    		this.btnPatientClear.Text = "Làm mới";
    		this.btnPatientClear.UseVisualStyleBackColor = false;
    		this.btnPatientClear.Click += new System.EventHandler(btnPatientClear_Click);
    		this.btnPatientUpdate.BackColor = System.Drawing.Color.FromArgb(25, 118, 210);
    		this.btnPatientUpdate.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
    		this.btnPatientUpdate.ForeColor = System.Drawing.Color.White;
    		this.btnPatientUpdate.Location = new System.Drawing.Point(160, 560);
    		this.btnPatientUpdate.Name = "btnPatientUpdate";
    		this.btnPatientUpdate.Size = new System.Drawing.Size(100, 35);
    		this.btnPatientUpdate.TabIndex = 26;
    		this.btnPatientUpdate.Text = "Cập nhật";
    		this.btnPatientUpdate.UseVisualStyleBackColor = false;
    		this.btnPatientUpdate.Click += new System.EventHandler(btnPatientUpdate_Click);
    		this.btnPatientAdd.BackColor = System.Drawing.Color.FromArgb(25, 118, 210);
    		this.btnPatientAdd.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
    		this.btnPatientAdd.ForeColor = System.Drawing.Color.White;
    		this.btnPatientAdd.Location = new System.Drawing.Point(40, 560);
    		this.btnPatientAdd.Name = "btnPatientAdd";
    		this.btnPatientAdd.Size = new System.Drawing.Size(100, 35);
    		this.btnPatientAdd.TabIndex = 25;
    		this.btnPatientAdd.Text = "Thêm mới";
    		this.btnPatientAdd.UseVisualStyleBackColor = false;
    		this.btnPatientAdd.Click += new System.EventHandler(btnPatientAdd_Click);
    		this.txtPatientUsernameDb.Location = new System.Drawing.Point(160, 485);
    		this.txtPatientUsernameDb.Visible = false;
    		this.txtPatientUsernameDb.Name = "txtPatientUsernameDb";
    		this.txtPatientUsernameDb.ReadOnly = true;
    		this.txtPatientUsernameDb.Size = new System.Drawing.Size(250, 30);
    		this.txtPatientUsernameDb.TabIndex = 24;
    		this.lblPatientUsernameDb.AutoSize = true;
    		this.lblPatientUsernameDb.Visible = false;
    		this.lblPatientUsernameDb.ForeColor = System.Drawing.Color.FromArgb(38, 50, 56);
    		this.lblPatientUsernameDb.Location = new System.Drawing.Point(15, 488);
    		this.lblPatientUsernameDb.Name = "lblPatientUsernameDb";
    		this.lblPatientUsernameDb.Size = new System.Drawing.Size(123, 23);
    		this.lblPatientUsernameDb.TabIndex = 23;
    		this.lblPatientUsernameDb.Text = "Username DB:";
    		this.txtPatientDrugAllergies.Location = new System.Drawing.Point(160, 470);
    		this.txtPatientDrugAllergies.Name = "txtPatientDrugAllergies";
    		this.txtPatientDrugAllergies.Size = new System.Drawing.Size(250, 30);
    		this.txtPatientDrugAllergies.TabIndex = 22;
    		this.lblPatientDrugAllergies.AutoSize = true;
    		this.lblPatientDrugAllergies.ForeColor = System.Drawing.Color.FromArgb(38, 50, 56);
    		this.lblPatientDrugAllergies.Location = new System.Drawing.Point(15, 473);
    		this.lblPatientDrugAllergies.Name = "lblPatientDrugAllergies";
    		this.lblPatientDrugAllergies.Size = new System.Drawing.Size(107, 23);
    		this.lblPatientDrugAllergies.TabIndex = 21;
    		this.lblPatientDrugAllergies.Text = "Dị ứng thuốc:";
    		this.txtPatientFamilyMedicalHistory.Location = new System.Drawing.Point(160, 430);
    		this.txtPatientFamilyMedicalHistory.Name = "txtPatientFamilyMedicalHistory";
    		this.txtPatientFamilyMedicalHistory.Size = new System.Drawing.Size(250, 30);
    		this.txtPatientFamilyMedicalHistory.TabIndex = 20;
    		this.lblPatientFamilyMedicalHistory.AutoSize = true;
    		this.lblPatientFamilyMedicalHistory.ForeColor = System.Drawing.Color.FromArgb(38, 50, 56);
    		this.lblPatientFamilyMedicalHistory.Location = new System.Drawing.Point(15, 433);
    		this.lblPatientFamilyMedicalHistory.Name = "lblPatientFamilyMedicalHistory";
    		this.lblPatientFamilyMedicalHistory.Size = new System.Drawing.Size(117, 23);
    		this.lblPatientFamilyMedicalHistory.TabIndex = 19;
    		this.lblPatientFamilyMedicalHistory.Text = "Tiền sử gia đình:";
    		this.txtPatientMedicalHistory.Location = new System.Drawing.Point(160, 390);
    		this.txtPatientMedicalHistory.Name = "txtPatientMedicalHistory";
    		this.txtPatientMedicalHistory.Size = new System.Drawing.Size(250, 30);
    		this.txtPatientMedicalHistory.TabIndex = 18;
    		this.lblPatientMedicalHistory.AutoSize = true;
    		this.lblPatientMedicalHistory.ForeColor = System.Drawing.Color.FromArgb(38, 50, 56);
    		this.lblPatientMedicalHistory.Location = new System.Drawing.Point(15, 393);
    		this.lblPatientMedicalHistory.Name = "lblPatientMedicalHistory";
    		this.lblPatientMedicalHistory.Size = new System.Drawing.Size(102, 23);
    		this.lblPatientMedicalHistory.TabIndex = 17;
    		this.lblPatientMedicalHistory.Text = "Tiền sử bệnh:";
    		this.txtPatientCityProvince.Location = new System.Drawing.Point(160, 350);
    		this.txtPatientCityProvince.Name = "txtPatientCityProvince";
    		this.txtPatientCityProvince.Size = new System.Drawing.Size(250, 30);
    		this.txtPatientCityProvince.TabIndex = 16;
    		this.lblPatientCityProvince.AutoSize = true;
    		this.lblPatientCityProvince.ForeColor = System.Drawing.Color.FromArgb(38, 50, 56);
    		this.lblPatientCityProvince.Location = new System.Drawing.Point(15, 353);
    		this.lblPatientCityProvince.Name = "lblPatientCityProvince";
    		this.lblPatientCityProvince.Size = new System.Drawing.Size(135, 23);
    		this.lblPatientCityProvince.TabIndex = 15;
    		this.lblPatientCityProvince.Text = "Tỉnh/Thành phố:";
    		this.txtPatientDistrict.Location = new System.Drawing.Point(160, 310);
    		this.txtPatientDistrict.Name = "txtPatientDistrict";
    		this.txtPatientDistrict.Size = new System.Drawing.Size(250, 30);
    		this.txtPatientDistrict.TabIndex = 14;
    		this.lblPatientDistrict.AutoSize = true;
    		this.lblPatientDistrict.ForeColor = System.Drawing.Color.FromArgb(38, 50, 56);
    		this.lblPatientDistrict.Location = new System.Drawing.Point(15, 313);
    		this.lblPatientDistrict.Name = "lblPatientDistrict";
    		this.lblPatientDistrict.Size = new System.Drawing.Size(111, 23);
    		this.lblPatientDistrict.TabIndex = 13;
    		this.lblPatientDistrict.Text = "Quận/Huyện:";
    		this.txtPatientStreet.Location = new System.Drawing.Point(160, 270);
    		this.txtPatientStreet.Name = "txtPatientStreet";
    		this.txtPatientStreet.Size = new System.Drawing.Size(250, 30);
    		this.txtPatientStreet.TabIndex = 12;
    		this.lblPatientStreet.AutoSize = true;
    		this.lblPatientStreet.ForeColor = System.Drawing.Color.FromArgb(38, 50, 56);
    		this.lblPatientStreet.Location = new System.Drawing.Point(15, 273);
    		this.lblPatientStreet.Name = "lblPatientStreet";
    		this.lblPatientStreet.Size = new System.Drawing.Size(100, 23);
    		this.lblPatientStreet.TabIndex = 11;
    		this.lblPatientStreet.Text = "Tên đường:";
    		this.txtPatientHouseNo.Location = new System.Drawing.Point(160, 230);
    		this.txtPatientHouseNo.Name = "txtPatientHouseNo";
    		this.txtPatientHouseNo.Size = new System.Drawing.Size(250, 30);
    		this.txtPatientHouseNo.TabIndex = 10;
    		this.lblPatientHouseNo.AutoSize = true;
    		this.lblPatientHouseNo.ForeColor = System.Drawing.Color.FromArgb(38, 50, 56);
    		this.lblPatientHouseNo.Location = new System.Drawing.Point(15, 233);
    		this.lblPatientHouseNo.Name = "lblPatientHouseNo";
    		this.lblPatientHouseNo.Size = new System.Drawing.Size(67, 23);
    		this.lblPatientHouseNo.TabIndex = 9;
    		this.lblPatientHouseNo.Text = "Số nhà:";
    		this.txtPatientIdCard.Location = new System.Drawing.Point(160, 190);
    		this.txtPatientIdCard.Name = "txtPatientIdCard";
    		this.txtPatientIdCard.Size = new System.Drawing.Size(250, 30);
    		this.txtPatientIdCard.TabIndex = 8;
    		this.lblPatientIdCard.AutoSize = true;
    		this.lblPatientIdCard.ForeColor = System.Drawing.Color.FromArgb(38, 50, 56);
    		this.lblPatientIdCard.Location = new System.Drawing.Point(15, 193);
    		this.lblPatientIdCard.Name = "lblPatientIdCard";
    		this.lblPatientIdCard.Size = new System.Drawing.Size(59, 23);
    		this.lblPatientIdCard.TabIndex = 7;
    		this.lblPatientIdCard.Text = "CCCD:";
    		this.txtPatientBirthDate.Location = new System.Drawing.Point(160, 150);
    		this.txtPatientBirthDate.Name = "txtPatientBirthDate";
    		this.txtPatientBirthDate.Size = new System.Drawing.Size(250, 30);
    		this.txtPatientBirthDate.TabIndex = 6;
    		this.lblPatientBirthDate.AutoSize = true;
    		this.lblPatientBirthDate.ForeColor = System.Drawing.Color.FromArgb(38, 50, 56);
    		this.lblPatientBirthDate.Location = new System.Drawing.Point(15, 153);
    		this.lblPatientBirthDate.Name = "lblPatientBirthDate";
    		this.lblPatientBirthDate.Size = new System.Drawing.Size(87, 23);
    		this.lblPatientBirthDate.TabIndex = 5;
    		this.lblPatientBirthDate.Text = "Ngày sinh:";
    		this.txtPatientGender.Location = new System.Drawing.Point(160, 110);
    		this.txtPatientGender.Name = "txtPatientGender";
    		this.txtPatientGender.Size = new System.Drawing.Size(250, 30);
    		this.txtPatientGender.TabIndex = 4;
    		this.lblPatientGender.AutoSize = true;
    		this.lblPatientGender.ForeColor = System.Drawing.Color.FromArgb(38, 50, 56);
    		this.lblPatientGender.Location = new System.Drawing.Point(15, 113);
    		this.lblPatientGender.Name = "lblPatientGender";
    		this.lblPatientGender.Size = new System.Drawing.Size(79, 23);
    		this.lblPatientGender.TabIndex = 3;
    		this.lblPatientGender.Text = "Giới tính:";
    		this.txtPatientFullName.Location = new System.Drawing.Point(160, 70);
    		this.txtPatientFullName.Name = "txtPatientFullName";
    		this.txtPatientFullName.Size = new System.Drawing.Size(250, 30);
    		this.txtPatientFullName.TabIndex = 2;
    		this.lblPatientFullName.AutoSize = true;
    		this.lblPatientFullName.ForeColor = System.Drawing.Color.FromArgb(38, 50, 56);
    		this.lblPatientFullName.Location = new System.Drawing.Point(15, 73);
    		this.lblPatientFullName.Name = "lblPatientFullName";
    		this.lblPatientFullName.Size = new System.Drawing.Size(88, 23);
    		this.lblPatientFullName.TabIndex = 1;
    		this.lblPatientFullName.Text = "Họ và tên:";
    		this.txtPatientId.Location = new System.Drawing.Point(160, 30);
    		this.txtPatientId.Name = "txtPatientId";
    		this.txtPatientId.Size = new System.Drawing.Size(250, 30);
    		this.txtPatientId.TabIndex = 1;
    		this.lblPatientId.AutoSize = true;
    		this.lblPatientId.ForeColor = System.Drawing.Color.FromArgb(38, 50, 56);
    		this.lblPatientId.Location = new System.Drawing.Point(15, 33);
    		this.lblPatientId.Name = "lblPatientId";
    		this.lblPatientId.Size = new System.Drawing.Size(126, 23);
    		this.lblPatientId.TabIndex = 0;
    		this.lblPatientId.Text = "Mã bệnh nhân:";
    		this.tabCreateMR.Controls.Add(this.grpCreateMR);
    		this.tabCreateMR.Location = new System.Drawing.Point(4, 32);
    		this.tabCreateMR.Name = "tabCreateMR";
    		this.tabCreateMR.Padding = new System.Windows.Forms.Padding(3);
    		this.tabCreateMR.Size = new System.Drawing.Size(1192, 714);
    		this.tabCreateMR.TabIndex = 1;
    		this.tabCreateMR.Text = "Lập hồ sơ bệnh án";
    		this.tabCreateMR.UseVisualStyleBackColor = true;
    		this.grpCreateMR.Anchor = System.Windows.Forms.AnchorStyles.None;
    		this.grpCreateMR.BackColor = System.Drawing.Color.White;
    		this.grpCreateMR.Controls.Add(this.btnMRCreate);
    		this.grpCreateMR.Controls.Add(this.label5);
    		this.grpCreateMR.Controls.Add(this.txtMRServiceResult);
    		this.grpCreateMR.Controls.Add(this.lblMRServiceResult);
    		this.grpCreateMR.Controls.Add(this.txtMRConclusion);
    		this.grpCreateMR.Controls.Add(this.lblMRConclusion);
    		this.grpCreateMR.Controls.Add(this.txtMRTreatmentPlan);
    		this.grpCreateMR.Controls.Add(this.lblMRTreatmentPlan);
    		this.grpCreateMR.Controls.Add(this.txtMRDiagnosis);
    		this.grpCreateMR.Controls.Add(this.lblMRDiagnosis);
    		this.grpCreateMR.Controls.Add(this.lblSectionSpecialty);
    		this.grpCreateMR.Controls.Add(this.cmbMRDoctorId);
    		this.grpCreateMR.Controls.Add(this.lblMRDoctorId);
    		this.grpCreateMR.Controls.Add(this.cmbMRDeptId);
    		this.grpCreateMR.Controls.Add(this.lblMRDeptId);
    		this.grpCreateMR.Controls.Add(this.lblSectionDoctor);
    		this.grpCreateMR.Controls.Add(this.dtpMRRecordDate);
    		this.grpCreateMR.Controls.Add(this.lblMRRecordDate);
    		this.grpCreateMR.Controls.Add(this.cmbMRPatientId);
    		this.grpCreateMR.Controls.Add(this.lblMRPatientId);
    		this.grpCreateMR.Controls.Add(this.txtMRRecordId);
    		this.grpCreateMR.Controls.Add(this.lblMRRecordId);
    		this.grpCreateMR.Controls.Add(this.lblSectionInfo);
    		this.grpCreateMR.ForeColor = System.Drawing.Color.FromArgb(25, 118, 210);
    		this.grpCreateMR.Location = new System.Drawing.Point(196, 47);
    		this.grpCreateMR.Name = "grpCreateMR";
    		this.grpCreateMR.Size = new System.Drawing.Size(800, 620);
    		this.grpCreateMR.TabIndex = 0;
    		this.grpCreateMR.TabStop = false;
    		this.btnMRCreate.BackColor = System.Drawing.Color.FromArgb(25, 118, 210);
    		this.btnMRCreate.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
    		this.btnMRCreate.Font = new System.Drawing.Font("Segoe UI", 12f, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
    		this.btnMRCreate.ForeColor = System.Drawing.Color.White;
    		this.btnMRCreate.Location = new System.Drawing.Point(300, 560);
    		this.btnMRCreate.Name = "btnMRCreate";
    		this.btnMRCreate.Size = new System.Drawing.Size(200, 45);
    		this.btnMRCreate.TabIndex = 22;
    		this.btnMRCreate.Text = "TẠO HỒ SƠ BỆNH ÁN";
    		this.btnMRCreate.UseVisualStyleBackColor = false;
    		this.btnMRCreate.Click += new System.EventHandler(btnMRCreate_Click);
    		this.label5.AutoSize = true;
    		this.label5.Font = new System.Drawing.Font("Segoe UI", 9f, System.Drawing.FontStyle.Italic, System.Drawing.GraphicsUnit.Point);
    		this.label5.ForeColor = System.Drawing.Color.FromArgb(211, 47, 47);
    		this.label5.Location = new System.Drawing.Point(40, 520);
    		this.label5.Name = "label5";
    		this.label5.Size = new System.Drawing.Size(434, 20);
    		this.label5.TabIndex = 13;
    		this.label5.Text = "* Ghi chú: Điều phối viên không có quyền chỉnh sửa thông tin chuyên môn";
    		this.label5.Visible = false;
    		this.txtMRServiceResult.BackColor = System.Drawing.Color.FromArgb(236, 239, 241);
    		this.txtMRServiceResult.Location = new System.Drawing.Point(540, 390);
    		this.txtMRServiceResult.Multiline = true;
    		this.txtMRServiceResult.Name = "txtMRServiceResult";
    		this.txtMRServiceResult.ReadOnly = true;
    		this.txtMRServiceResult.Size = new System.Drawing.Size(220, 100);
    		this.txtMRServiceResult.TabIndex = 20;
    		this.lblMRServiceResult.AutoSize = true;
    		this.lblMRServiceResult.ForeColor = System.Drawing.Color.FromArgb(38, 50, 56);
    		this.lblMRServiceResult.Location = new System.Drawing.Point(540, 360);
    		this.lblMRServiceResult.Name = "lblMRServiceResult";
    		this.lblMRServiceResult.Size = new System.Drawing.Size(133, 23);
    		this.lblMRServiceResult.TabIndex = 19;
    		this.lblMRServiceResult.Text = "Kết quả dịch vụ:";
    		this.txtMRConclusion.BackColor = System.Drawing.Color.FromArgb(236, 239, 241);
    		this.txtMRConclusion.Location = new System.Drawing.Point(290, 390);
    		this.txtMRConclusion.Multiline = true;
    		this.txtMRConclusion.Name = "txtMRConclusion";
    		this.txtMRConclusion.ReadOnly = true;
    		this.txtMRConclusion.Size = new System.Drawing.Size(220, 100);
    		this.txtMRConclusion.TabIndex = 18;
    		this.lblMRConclusion.AutoSize = true;
    		this.lblMRConclusion.ForeColor = System.Drawing.Color.FromArgb(38, 50, 56);
    		this.lblMRConclusion.Location = new System.Drawing.Point(290, 360);
    		this.lblMRConclusion.Name = "lblMRConclusion";
    		this.lblMRConclusion.Size = new System.Drawing.Size(77, 23);
    		this.lblMRConclusion.TabIndex = 17;
    		this.lblMRConclusion.Text = "Kết luận:";
    		this.txtMRTreatmentPlan.BackColor = System.Drawing.Color.FromArgb(236, 239, 241);
    		this.txtMRTreatmentPlan.Location = new System.Drawing.Point(40, 450);
    		this.txtMRTreatmentPlan.Multiline = true;
    		this.txtMRTreatmentPlan.Name = "txtMRTreatmentPlan";
    		this.txtMRTreatmentPlan.ReadOnly = true;
    		this.txtMRTreatmentPlan.Size = new System.Drawing.Size(220, 40);
    		this.txtMRTreatmentPlan.TabIndex = 16;
    		this.lblMRTreatmentPlan.AutoSize = true;
    		this.lblMRTreatmentPlan.ForeColor = System.Drawing.Color.FromArgb(38, 50, 56);
    		this.lblMRTreatmentPlan.Location = new System.Drawing.Point(40, 420);
    		this.lblMRTreatmentPlan.Name = "lblMRTreatmentPlan";
    		this.lblMRTreatmentPlan.Size = new System.Drawing.Size(130, 23);
    		this.lblMRTreatmentPlan.TabIndex = 15;
    		this.lblMRTreatmentPlan.Text = "Hướng điều trị:";
    		this.txtMRDiagnosis.BackColor = System.Drawing.Color.FromArgb(236, 239, 241);
    		this.txtMRDiagnosis.Location = new System.Drawing.Point(40, 370);
    		this.txtMRDiagnosis.Multiline = true;
    		this.txtMRDiagnosis.Name = "txtMRDiagnosis";
    		this.txtMRDiagnosis.ReadOnly = true;
    		this.txtMRDiagnosis.Size = new System.Drawing.Size(220, 40);
    		this.txtMRDiagnosis.TabIndex = 14;
    		this.lblMRDiagnosis.AutoSize = true;
    		this.lblMRDiagnosis.ForeColor = System.Drawing.Color.FromArgb(38, 50, 56);
    		this.lblMRDiagnosis.Location = new System.Drawing.Point(40, 340);
    		this.lblMRDiagnosis.Name = "lblMRDiagnosis";
    		this.lblMRDiagnosis.Size = new System.Drawing.Size(95, 23);
    		this.lblMRDiagnosis.TabIndex = 13;
    		this.lblMRDiagnosis.Text = "Chẩn đoán:";
    		this.lblSectionSpecialty.AutoSize = true;
    		this.lblSectionSpecialty.Font = new System.Drawing.Font("Segoe UI", 11f, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
    		this.lblSectionSpecialty.Location = new System.Drawing.Point(20, 300);
    		this.lblSectionSpecialty.Name = "lblSectionSpecialty";
    		this.lblSectionSpecialty.Size = new System.Drawing.Size(242, 25);
    		this.lblSectionSpecialty.TabIndex = 12;
    		this.lblSectionSpecialty.Text = "3. Thông tin chuyên môn";
    		this.cmbMRDoctorId.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDown;
    		this.cmbMRDoctorId.FormattingEnabled = true;
    		this.cmbMRDoctorId.Location = new System.Drawing.Point(220, 230);
    		this.cmbMRDoctorId.Name = "cmbMRDoctorId";
    		this.cmbMRDoctorId.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.SuggestAppend;
    		this.cmbMRDoctorId.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.ListItems;
    		this.cmbMRDoctorId.Size = new System.Drawing.Size(280, 31);
    		this.cmbMRDoctorId.TabIndex = 11;
    		this.lblMRDoctorId.AutoSize = true;
    		this.lblMRDoctorId.ForeColor = System.Drawing.Color.FromArgb(38, 50, 56);
    		this.lblMRDoctorId.Location = new System.Drawing.Point(40, 233);
    		this.lblMRDoctorId.Name = "lblMRDoctorId";
    		this.lblMRDoctorId.Size = new System.Drawing.Size(142, 23);
    		this.lblMRDoctorId.TabIndex = 10;
    		this.lblMRDoctorId.Text = "Bác sĩ phụ trách:";
    		this.cmbMRDeptId.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
    		this.cmbMRDeptId.FormattingEnabled = true;
    		this.cmbMRDeptId.Location = new System.Drawing.Point(220, 190);
    		this.cmbMRDeptId.Name = "cmbMRDeptId";
    		this.cmbMRDeptId.Size = new System.Drawing.Size(250, 31);
    		this.cmbMRDeptId.TabIndex = 9;
    		this.cmbMRDeptId.SelectedIndexChanged += new System.EventHandler(cmbUnifiedDept_SelectedIndexChanged);
    		this.lblMRDeptId.AutoSize = true;
    		this.lblMRDeptId.ForeColor = System.Drawing.Color.FromArgb(38, 50, 56);
    		this.lblMRDeptId.Location = new System.Drawing.Point(40, 193);
    		this.lblMRDeptId.Name = "lblMRDeptId";
    		this.lblMRDeptId.Size = new System.Drawing.Size(120, 23);
    		this.lblMRDeptId.TabIndex = 8;
    		this.lblMRDeptId.Text = "Khoa điều trị:";
    		this.lblSectionDoctor.AutoSize = true;
    		this.lblSectionDoctor.Font = new System.Drawing.Font("Segoe UI", 11f, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
    		this.lblSectionDoctor.Location = new System.Drawing.Point(20, 150);
    		this.lblSectionDoctor.Name = "lblSectionDoctor";
    		this.lblSectionDoctor.Size = new System.Drawing.Size(192, 25);
    		this.lblSectionDoctor.TabIndex = 7;
    		this.lblSectionDoctor.Text = "2. Phân công bác sĩ";
    		this.dtpMRRecordDate.Format = System.Windows.Forms.DateTimePickerFormat.Short;
    		this.dtpMRRecordDate.Location = new System.Drawing.Point(540, 90);
    		this.dtpMRRecordDate.Name = "dtpMRRecordDate";
    		this.dtpMRRecordDate.Size = new System.Drawing.Size(200, 30);
    		this.dtpMRRecordDate.TabIndex = 6;
    		this.lblMRRecordDate.AutoSize = true;
    		this.lblMRRecordDate.ForeColor = System.Drawing.Color.FromArgb(38, 50, 56);
    		this.lblMRRecordDate.Location = new System.Drawing.Point(540, 60);
    		this.lblMRRecordDate.Name = "lblMRRecordDate";
    		this.lblMRRecordDate.Size = new System.Drawing.Size(82, 23);
    		this.lblMRRecordDate.TabIndex = 5;
    		this.lblMRRecordDate.Text = "Ngày lập";
    		this.cmbMRPatientId.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDown;
    		this.cmbMRPatientId.FormattingEnabled = true;
    		this.cmbMRPatientId.Location = new System.Drawing.Point(220, 90);
    		this.cmbMRPatientId.Name = "cmbMRPatientId";
    		this.cmbMRPatientId.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.SuggestAppend;
    		this.cmbMRPatientId.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.ListItems;
    		this.cmbMRPatientId.Size = new System.Drawing.Size(280, 31);
    		this.cmbMRPatientId.TabIndex = 4;
    		this.lblMRPatientId.AutoSize = true;
    		this.lblMRPatientId.ForeColor = System.Drawing.Color.FromArgb(38, 50, 56);
    		this.lblMRPatientId.Location = new System.Drawing.Point(220, 60);
    		this.lblMRPatientId.Name = "lblMRPatientId";
    		this.lblMRPatientId.Size = new System.Drawing.Size(91, 23);
    		this.lblMRPatientId.TabIndex = 3;
    		this.lblMRPatientId.Text = "Bệnh nhân";
    		this.txtMRRecordId.Location = new System.Drawing.Point(40, 90);
    		this.txtMRRecordId.Name = "txtMRRecordId";
    		this.txtMRRecordId.Size = new System.Drawing.Size(150, 30);
    		this.txtMRRecordId.TabIndex = 2;
    		this.lblMRRecordId.AutoSize = true;
    		this.lblMRRecordId.ForeColor = System.Drawing.Color.FromArgb(38, 50, 56);
    		this.lblMRRecordId.Location = new System.Drawing.Point(40, 60);
    		this.lblMRRecordId.Name = "lblMRRecordId";
    		this.lblMRRecordId.Size = new System.Drawing.Size(81, 23);
    		this.lblMRRecordId.TabIndex = 1;
    		this.lblMRRecordId.Text = "Ma HSBA";
    		this.lblSectionInfo.AutoSize = true;
    		this.lblSectionInfo.Font = new System.Drawing.Font("Segoe UI", 11f, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
    		this.lblSectionInfo.Location = new System.Drawing.Point(20, 30);
    		this.lblSectionInfo.Name = "lblSectionInfo";
    		this.lblSectionInfo.Size = new System.Drawing.Size(242, 25);
    		this.lblSectionInfo.TabIndex = 0;
    		this.lblSectionInfo.Text = "1. Thông tin hồ sơ bệnh án";
    		this.tabAssignDoctor.Controls.Add(this.splitContainer2);
    		this.tabAssignDoctor.Location = new System.Drawing.Point(4, 32);
    		this.tabAssignDoctor.Name = "tabAssignDoctor";
    		this.tabAssignDoctor.Padding = new System.Windows.Forms.Padding(3);
    		this.tabAssignDoctor.Size = new System.Drawing.Size(1192, 714);
    		this.tabAssignDoctor.TabIndex = 2;
    		this.tabAssignDoctor.Text = "Phân công Bác sĩ/Khoa";
    		this.tabAssignDoctor.UseVisualStyleBackColor = true;
    		this.splitContainer2.Dock = System.Windows.Forms.DockStyle.Fill;
    		this.splitContainer2.FixedPanel = System.Windows.Forms.FixedPanel.Panel2;
    		this.splitContainer2.Location = new System.Drawing.Point(3, 3);
    		this.splitContainer2.Name = "splitContainer2";
    		this.splitContainer2.Panel1.Controls.Add(this.dgvMedicalRecords);
    		this.splitContainer2.Panel2.Controls.Add(this.groupBox1);
    		this.splitContainer2.Size = new System.Drawing.Size(1186, 708);
    		this.splitContainer2.SplitterDistance = 600;
    		this.splitContainer2.TabIndex = 0;
    		this.dgvMedicalRecords.AllowUserToAddRows = false;
    		this.dgvMedicalRecords.AllowUserToDeleteRows = false;
    		this.dgvMedicalRecords.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
    		this.dgvMedicalRecords.BackgroundColor = System.Drawing.Color.White;
    		this.dgvMedicalRecords.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
    		this.dgvMedicalRecords.Dock = System.Windows.Forms.DockStyle.Fill;
    		this.dgvMedicalRecords.EnableHeadersVisualStyles = false;
    		this.dgvMedicalRecords.Location = new System.Drawing.Point(0, 0);
    		this.dgvMedicalRecords.Name = "dgvMedicalRecords";
    		this.dgvMedicalRecords.ReadOnly = true;
    		this.dgvMedicalRecords.RowHeadersWidth = 51;
    		this.dgvMedicalRecords.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
    		this.dgvMedicalRecords.Size = new System.Drawing.Size(600, 708);
    		this.dgvMedicalRecords.TabIndex = 0;
    		this.dgvMedicalRecords.CellClick += new System.Windows.Forms.DataGridViewCellEventHandler(dgvMedicalRecords_CellClick);
    		this.groupBox1.BackColor = System.Drawing.Color.White;
    		this.groupBox1.Controls.Add(this.btnUpdateAssignDoctor);
    		this.groupBox1.Controls.Add(this.cmbAssignDoctor);
    		this.groupBox1.Controls.Add(this.label9);
    		this.groupBox1.Controls.Add(this.cmbAssignDept);
    		this.groupBox1.Controls.Add(this.label10);
    		this.groupBox1.Controls.Add(this.txtAssignMRDate);
    		this.groupBox1.Controls.Add(this.label8);
    		this.groupBox1.Controls.Add(this.txtAssignMRPatient);
    		this.groupBox1.Controls.Add(this.label7);
    		this.groupBox1.Controls.Add(this.txtAssignMRId);
    		this.groupBox1.Controls.Add(this.label6);
    		this.groupBox1.Dock = System.Windows.Forms.DockStyle.Fill;
    		this.groupBox1.ForeColor = System.Drawing.Color.FromArgb(25, 118, 210);
    		this.groupBox1.Location = new System.Drawing.Point(0, 0);
    		this.groupBox1.Name = "groupBox1";
    		this.groupBox1.Size = new System.Drawing.Size(582, 708);
    		this.groupBox1.TabIndex = 0;
    		this.groupBox1.TabStop = false;
    		this.groupBox1.Text = "Phân công Bác sĩ cho Hồ sơ bệnh án";
    		this.btnUpdateAssignDoctor.BackColor = System.Drawing.Color.FromArgb(25, 118, 210);
    		this.btnUpdateAssignDoctor.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
    		this.btnUpdateAssignDoctor.ForeColor = System.Drawing.Color.White;
    		this.btnUpdateAssignDoctor.Location = new System.Drawing.Point(180, 270);
    		this.btnUpdateAssignDoctor.Name = "btnUpdateAssignDoctor";
    		this.btnUpdateAssignDoctor.Size = new System.Drawing.Size(200, 40);
    		this.btnUpdateAssignDoctor.TabIndex = 10;
    		this.btnUpdateAssignDoctor.Text = "Cập nhật phân công";
    		this.btnUpdateAssignDoctor.UseVisualStyleBackColor = false;
    		this.btnUpdateAssignDoctor.Click += new System.EventHandler(btnUpdateAssignDoctor_Click);
    		this.cmbAssignDoctor.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDown;
    		this.cmbAssignDoctor.FormattingEnabled = true;
    		this.cmbAssignDoctor.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.SuggestAppend;
    		this.cmbAssignDoctor.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.ListItems;
    		this.cmbAssignDoctor.Location = new System.Drawing.Point(180, 210);
    		this.cmbAssignDoctor.Name = "cmbAssignDoctor";
    		this.cmbAssignDoctor.Size = new System.Drawing.Size(250, 31);
    		this.cmbAssignDoctor.TabIndex = 9;
    		this.label9.AutoSize = true;
    		this.label9.ForeColor = System.Drawing.Color.FromArgb(38, 50, 56);
    		this.label9.Location = new System.Drawing.Point(40, 213);
    		this.label9.Name = "label9";
    		this.label9.Size = new System.Drawing.Size(142, 23);
    		this.label9.TabIndex = 8;
    		this.label9.Text = "Bác sĩ phụ trách:";
    		this.cmbAssignDept.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDown;
    		this.cmbAssignDept.FormattingEnabled = true;
    		this.cmbAssignDept.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.SuggestAppend;
    		this.cmbAssignDept.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.ListItems;
    		this.cmbAssignDept.Location = new System.Drawing.Point(180, 170);
    		this.cmbAssignDept.Name = "cmbAssignDept";
    		this.cmbAssignDept.Size = new System.Drawing.Size(250, 31);
    		this.cmbAssignDept.TabIndex = 7;
    		this.cmbAssignDept.SelectedIndexChanged += new System.EventHandler(cmbAssignDept_SelectedIndexChanged);
    		this.label10.AutoSize = true;
    		this.label10.ForeColor = System.Drawing.Color.FromArgb(38, 50, 56);
    		this.label10.Location = new System.Drawing.Point(40, 173);
    		this.label10.Name = "label10";
    		this.label10.Size = new System.Drawing.Size(120, 23);
    		this.label10.TabIndex = 6;
    		this.label10.Text = "Khoa điều trị:";
    		this.txtAssignMRDate.BackColor = System.Drawing.Color.FromArgb(236, 239, 241);
    		this.txtAssignMRDate.Location = new System.Drawing.Point(180, 130);
    		this.txtAssignMRDate.Name = "txtAssignMRDate";
    		this.txtAssignMRDate.ReadOnly = true;
    		this.txtAssignMRDate.Size = new System.Drawing.Size(250, 30);
    		this.txtAssignMRDate.TabIndex = 5;
    		this.label8.AutoSize = true;
    		this.label8.ForeColor = System.Drawing.Color.FromArgb(38, 50, 56);
    		this.label8.Location = new System.Drawing.Point(40, 133);
    		this.label8.Name = "label8";
    		this.label8.Size = new System.Drawing.Size(82, 23);
    		this.label8.TabIndex = 4;
    		this.label8.Text = "Ngày lập:";
    		this.txtAssignMRPatient.BackColor = System.Drawing.Color.FromArgb(236, 239, 241);
    		this.txtAssignMRPatient.Location = new System.Drawing.Point(180, 90);
    		this.txtAssignMRPatient.Name = "txtAssignMRPatient";
    		this.txtAssignMRPatient.ReadOnly = true;
    		this.txtAssignMRPatient.Size = new System.Drawing.Size(250, 30);
    		this.txtAssignMRPatient.TabIndex = 3;
    		this.label7.AutoSize = true;
    		this.label7.ForeColor = System.Drawing.Color.FromArgb(38, 50, 56);
    		this.label7.Location = new System.Drawing.Point(40, 93);
    		this.label7.Name = "label7";
    		this.label7.Size = new System.Drawing.Size(95, 23);
    		this.label7.TabIndex = 2;
    		this.label7.Text = "Bệnh nhân:";
    		this.txtAssignMRId.BackColor = System.Drawing.Color.FromArgb(236, 239, 241);
    		this.txtAssignMRId.Location = new System.Drawing.Point(180, 50);
    		this.txtAssignMRId.Name = "txtAssignMRId";
    		this.txtAssignMRId.ReadOnly = true;
    		this.txtAssignMRId.Size = new System.Drawing.Size(250, 30);
    		this.txtAssignMRId.TabIndex = 1;
    		this.label6.AutoSize = true;
    		this.label6.ForeColor = System.Drawing.Color.FromArgb(38, 50, 56);
    		this.label6.Location = new System.Drawing.Point(40, 53);
    		this.label6.Name = "label6";
    		this.label6.Size = new System.Drawing.Size(85, 23);
    		this.label6.TabIndex = 0;
    		this.label6.Text = "Ma HSBA:";
    		this.tabAssignTech.Controls.Add(this.splitContainer3);
    		this.tabAssignTech.Location = new System.Drawing.Point(4, 32);
    		this.tabAssignTech.Name = "tabAssignTech";
    		this.tabAssignTech.Padding = new System.Windows.Forms.Padding(3);
    		this.tabAssignTech.Size = new System.Drawing.Size(1192, 714);
    		this.tabAssignTech.TabIndex = 3;
    		this.tabAssignTech.Text = "Phân công Kỹ thuật viên";
    		this.tabAssignTech.UseVisualStyleBackColor = true;
    		this.splitContainer3.Dock = System.Windows.Forms.DockStyle.Fill;
    		this.splitContainer3.FixedPanel = System.Windows.Forms.FixedPanel.Panel2;
    		this.splitContainer3.Location = new System.Drawing.Point(3, 3);
    		this.splitContainer3.Name = "splitContainer3";
    		this.splitContainer3.Panel1.Controls.Add(this.dgvServiceRecords);
    		this.splitContainer3.Panel1.Controls.Add(this.lblTechNotice);
    		this.splitContainer3.Panel2.Controls.Add(this.groupBox2);
    		this.splitContainer3.Size = new System.Drawing.Size(1186, 708);
    		this.splitContainer3.SplitterDistance = 600;
    		this.splitContainer3.TabIndex = 0;
    		this.dgvServiceRecords.AllowUserToAddRows = false;
    		this.dgvServiceRecords.AllowUserToDeleteRows = false;
    		this.dgvServiceRecords.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
    		this.dgvServiceRecords.BackgroundColor = System.Drawing.Color.White;
    		this.dgvServiceRecords.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
    		this.dgvServiceRecords.Dock = System.Windows.Forms.DockStyle.Fill;
    		this.dgvServiceRecords.EnableHeadersVisualStyles = false;
    		this.dgvServiceRecords.Location = new System.Drawing.Point(0, 30);
    		this.dgvServiceRecords.Name = "dgvServiceRecords";
    		this.dgvServiceRecords.ReadOnly = true;
    		this.dgvServiceRecords.RowHeadersWidth = 51;
    		this.dgvServiceRecords.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
    		this.dgvServiceRecords.Size = new System.Drawing.Size(600, 678);
    		this.dgvServiceRecords.TabIndex = 1;
    		this.dgvServiceRecords.CellClick += new System.Windows.Forms.DataGridViewCellEventHandler(dgvServiceRecords_CellClick);
    		this.dgvServiceRecords.CellFormatting += new System.Windows.Forms.DataGridViewCellFormattingEventHandler(dgvServiceRecords_CellFormatting);
    		this.lblTechNotice.Dock = System.Windows.Forms.DockStyle.Top;
    		this.lblTechNotice.Font = new System.Drawing.Font("Segoe UI", 9f, System.Drawing.FontStyle.Italic, System.Drawing.GraphicsUnit.Point);
    		this.lblTechNotice.ForeColor = System.Drawing.Color.FromArgb(211, 47, 47);
    		this.lblTechNotice.Location = new System.Drawing.Point(0, 0);
    		this.lblTechNotice.Name = "lblTechNotice";
    		this.lblTechNotice.Size = new System.Drawing.Size(600, 30);
    		this.lblTechNotice.TabIndex = 0;
    		this.lblTechNotice.Text = "* Chỉ hiển thị các dịch vụ chưa được phân công kỹ thuật viên";
    		this.lblTechNotice.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
    		this.groupBox2.BackColor = System.Drawing.Color.White;
    		this.groupBox2.Controls.Add(this.btnUpdateAssignTech);
    		this.groupBox2.Controls.Add(this.cmbAssignTech);
    		this.groupBox2.Controls.Add(this.label15);
    		this.groupBox2.Controls.Add(this.txtAssignSRDate);
    		this.groupBox2.Controls.Add(this.label13);
    		this.groupBox2.Controls.Add(this.txtAssignSRType);
    		this.groupBox2.Controls.Add(this.label12);
    		this.groupBox2.Controls.Add(this.txtAssignSRId);
    		this.groupBox2.Controls.Add(this.label11);
    		this.groupBox2.Dock = System.Windows.Forms.DockStyle.Fill;
    		this.groupBox2.ForeColor = System.Drawing.Color.FromArgb(25, 118, 210);
    		this.groupBox2.Location = new System.Drawing.Point(0, 0);
    		this.groupBox2.Name = "groupBox2";
    		this.groupBox2.Size = new System.Drawing.Size(582, 708);
    		this.groupBox2.TabIndex = 1;
    		this.groupBox2.TabStop = false;
    		this.groupBox2.Text = "Phân công Kỹ thuật viên cho Hồ sơ dịch vụ";
    		this.btnUpdateAssignTech.BackColor = System.Drawing.Color.FromArgb(25, 118, 210);
    		this.btnUpdateAssignTech.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
    		this.btnUpdateAssignTech.ForeColor = System.Drawing.Color.White;
    		this.btnUpdateAssignTech.Location = new System.Drawing.Point(180, 230);
    		this.btnUpdateAssignTech.Name = "btnUpdateAssignTech";
    		this.btnUpdateAssignTech.Size = new System.Drawing.Size(200, 40);
    		this.btnUpdateAssignTech.TabIndex = 10;
    		this.btnUpdateAssignTech.Text = "Cập nhật phân công";
    		this.btnUpdateAssignTech.UseVisualStyleBackColor = false;
    		this.btnUpdateAssignTech.Click += new System.EventHandler(btnUpdateAssignTech_Click);
    		this.cmbAssignTech.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDown;
    		this.cmbAssignTech.FormattingEnabled = true;
    		this.cmbAssignTech.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.SuggestAppend;
    		this.cmbAssignTech.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.ListItems;
    		this.cmbAssignTech.Location = new System.Drawing.Point(180, 170);
    		this.cmbAssignTech.Name = "cmbAssignTech";
    		this.cmbAssignTech.Size = new System.Drawing.Size(250, 31);
    		this.cmbAssignTech.TabIndex = 9;
    		this.label15.AutoSize = true;
    		this.label15.ForeColor = System.Drawing.Color.FromArgb(38, 50, 56);
    		this.label15.Location = new System.Drawing.Point(40, 173);
    		this.label15.Name = "label15";
    		this.label15.Size = new System.Drawing.Size(121, 23);
    		this.label15.TabIndex = 8;
    		this.label15.Text = "Kỹ thuật viên:";
    		this.txtAssignSRDate.BackColor = System.Drawing.Color.Gainsboro;
    		this.txtAssignSRDate.Location = new System.Drawing.Point(180, 130);
    		this.txtAssignSRDate.Name = "txtAssignSRDate";
    		this.txtAssignSRDate.ReadOnly = true;
    		this.txtAssignSRDate.Size = new System.Drawing.Size(250, 30);
    		this.txtAssignSRDate.TabIndex = 5;
    		this.label13.AutoSize = true;
    		this.label13.ForeColor = System.Drawing.Color.FromArgb(38, 50, 56);
    		this.label13.Location = new System.Drawing.Point(40, 133);
    		this.label13.Name = "label13";
    		this.label13.Size = new System.Drawing.Size(119, 23);
    		this.label13.TabIndex = 4;
    		this.label13.Text = "Ngày dịch vụ:";
    		this.txtAssignSRType.BackColor = System.Drawing.Color.Gainsboro;
    		this.txtAssignSRType.Location = new System.Drawing.Point(180, 90);
    		this.txtAssignSRType.Name = "txtAssignSRType";
    		this.txtAssignSRType.ReadOnly = true;
    		this.txtAssignSRType.Size = new System.Drawing.Size(250, 30);
    		this.txtAssignSRType.TabIndex = 3;
    		this.label12.AutoSize = true;
    		this.label12.ForeColor = System.Drawing.Color.FromArgb(38, 50, 56);
    		this.label12.Location = new System.Drawing.Point(40, 93);
    		this.label12.Name = "label12";
    		this.label12.Size = new System.Drawing.Size(110, 23);
    		this.label12.TabIndex = 2;
    		this.label12.Text = "Loại dịch vụ:";
    		this.txtAssignSRId.BackColor = System.Drawing.Color.Gainsboro;
    		this.txtAssignSRId.Location = new System.Drawing.Point(180, 50);
    		this.txtAssignSRId.Name = "txtAssignSRId";
    		this.txtAssignSRId.ReadOnly = true;
    		this.txtAssignSRId.Size = new System.Drawing.Size(250, 30);
    		this.txtAssignSRId.TabIndex = 1;
    		this.label11.AutoSize = true;
    		this.label11.ForeColor = System.Drawing.Color.FromArgb(38, 50, 56);
    		this.label11.Location = new System.Drawing.Point(40, 53);
    		this.label11.Name = "label11";
    		this.label11.Size = new System.Drawing.Size(85, 23);
    		this.label11.TabIndex = 0;
    		this.label11.Text = "Ma HSBA:";
    		this.tabProfile.Controls.Add(this.groupBox3);
    		this.tabProfile.Location = new System.Drawing.Point(4, 32);
    		this.tabProfile.Name = "tabProfile";
    		this.tabProfile.Padding = new System.Windows.Forms.Padding(3);
    		this.tabProfile.Size = new System.Drawing.Size(1192, 714);
    		this.tabProfile.TabIndex = 4;
    		this.tabProfile.Text = "Thông tin cá nhân";
    		this.tabProfile.UseVisualStyleBackColor = true;
    		this.groupBox3.Anchor = System.Windows.Forms.AnchorStyles.None;
    		this.groupBox3.BackColor = System.Drawing.Color.White;
    		this.groupBox3.Controls.Add(this.btnUpdateProfile);
    		this.groupBox3.Controls.Add(this.txtSelfHometown);
    		this.groupBox3.Controls.Add(this.label20);
    		this.groupBox3.Controls.Add(this.txtSelfPhone);
    		this.groupBox3.Controls.Add(this.label21);
    		this.groupBox3.Controls.Add(this.txtSelfSpecialty);
    		this.groupBox3.Controls.Add(this.label18);
    		this.groupBox3.Controls.Add(this.txtSelfRole);
    		this.groupBox3.Controls.Add(this.label19);
    		this.groupBox3.Controls.Add(this.txtSelfFullName);
    		this.groupBox3.Controls.Add(this.label17);
    		this.groupBox3.Controls.Add(this.txtSelfStaffId);
    		this.groupBox3.Controls.Add(this.label16);
    		this.groupBox3.ForeColor = System.Drawing.Color.FromArgb(25, 118, 210);
    		this.groupBox3.Location = new System.Drawing.Point(296, 107);
    		this.groupBox3.Name = "groupBox3";
    		this.groupBox3.Size = new System.Drawing.Size(600, 500);
    		this.groupBox3.TabIndex = 0;
    		this.groupBox3.TabStop = false;
    		this.groupBox3.Text = "Thông tin cá nhân Điều phối viên";
    		this.btnUpdateProfile.BackColor = System.Drawing.Color.FromArgb(25, 118, 210);
    		this.btnUpdateProfile.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
    		this.btnUpdateProfile.ForeColor = System.Drawing.Color.White;
    		this.btnUpdateProfile.Location = new System.Drawing.Point(200, 310);
    		this.btnUpdateProfile.Name = "btnUpdateProfile";
    		this.btnUpdateProfile.Size = new System.Drawing.Size(200, 40);
    		this.btnUpdateProfile.TabIndex = 12;
    		this.btnUpdateProfile.Text = "Cập nhật";
    		this.btnUpdateProfile.UseVisualStyleBackColor = false;
    		this.btnUpdateProfile.Click += new System.EventHandler(btnUpdateProfile_Click);
    		this.txtSelfHometown.Location = new System.Drawing.Point(180, 250);
    		this.txtSelfHometown.Name = "txtSelfHometown";
    		this.txtSelfHometown.Size = new System.Drawing.Size(250, 30);
    		this.txtSelfHometown.TabIndex = 11;
    		this.label20.AutoSize = true;
    		this.label20.ForeColor = System.Drawing.Color.FromArgb(38, 50, 56);
    		this.label20.Location = new System.Drawing.Point(40, 253);
    		this.label20.Name = "label20";
    		this.label20.Size = new System.Drawing.Size(88, 23);
    		this.label20.TabIndex = 10;
    		this.label20.Text = "Quê quán:";
    		this.txtSelfPhone.Location = new System.Drawing.Point(180, 210);
    		this.txtSelfPhone.Name = "txtSelfPhone";
    		this.txtSelfPhone.Size = new System.Drawing.Size(250, 30);
    		this.txtSelfPhone.TabIndex = 9;
    		this.label21.AutoSize = true;
    		this.label21.ForeColor = System.Drawing.Color.FromArgb(38, 50, 56);
    		this.label21.Location = new System.Drawing.Point(40, 213);
    		this.label21.Name = "label21";
    		this.label21.Size = new System.Drawing.Size(115, 23);
    		this.label21.TabIndex = 8;
    		this.label21.Text = "Số điện thoại:";
    		this.txtSelfSpecialty.BackColor = System.Drawing.Color.FromArgb(236, 239, 241);
    		this.txtSelfSpecialty.Location = new System.Drawing.Point(180, 170);
    		this.txtSelfSpecialty.Name = "txtSelfSpecialty";
    		this.txtSelfSpecialty.ReadOnly = true;
    		this.txtSelfSpecialty.Size = new System.Drawing.Size(250, 30);
    		this.txtSelfSpecialty.TabIndex = 7;
    		this.label18.AutoSize = true;
    		this.label18.ForeColor = System.Drawing.Color.FromArgb(38, 50, 56);
    		this.label18.Location = new System.Drawing.Point(40, 173);
    		this.label18.Name = "label18";
    		this.label18.Size = new System.Drawing.Size(113, 23);
    		this.label18.TabIndex = 6;
    		this.label18.Text = "Chuyên khoa:";
    		this.txtSelfRole.BackColor = System.Drawing.Color.FromArgb(236, 239, 241);
    		this.txtSelfRole.Location = new System.Drawing.Point(180, 130);
    		this.txtSelfRole.Name = "txtSelfRole";
    		this.txtSelfRole.ReadOnly = true;
    		this.txtSelfRole.Size = new System.Drawing.Size(250, 30);
    		this.txtSelfRole.TabIndex = 5;
    		this.label19.AutoSize = true;
    		this.label19.ForeColor = System.Drawing.Color.FromArgb(38, 50, 56);
    		this.label19.Location = new System.Drawing.Point(40, 133);
    		this.label19.Name = "label19";
    		this.label19.Size = new System.Drawing.Size(64, 23);
    		this.label19.TabIndex = 4;
    		this.label19.Text = "Vai trò:";
    		this.txtSelfFullName.BackColor = System.Drawing.Color.FromArgb(236, 239, 241);
    		this.txtSelfFullName.Location = new System.Drawing.Point(180, 90);
    		this.txtSelfFullName.Name = "txtSelfFullName";
    		this.txtSelfFullName.ReadOnly = true;
    		this.txtSelfFullName.Size = new System.Drawing.Size(250, 30);
    		this.txtSelfFullName.TabIndex = 3;
    		this.label17.AutoSize = true;
    		this.label17.ForeColor = System.Drawing.Color.FromArgb(38, 50, 56);
    		this.label17.Location = new System.Drawing.Point(40, 93);
    		this.label17.Name = "label17";
    		this.label17.Size = new System.Drawing.Size(66, 23);
    		this.label17.TabIndex = 2;
    		this.label17.Text = "Họ tên:";
    		this.txtSelfStaffId.BackColor = System.Drawing.Color.FromArgb(236, 239, 241);
    		this.txtSelfStaffId.Location = new System.Drawing.Point(180, 50);
    		this.txtSelfStaffId.Name = "txtSelfStaffId";
    		this.txtSelfStaffId.ReadOnly = true;
    		this.txtSelfStaffId.Size = new System.Drawing.Size(250, 30);
    		this.txtSelfStaffId.TabIndex = 1;
    		this.label16.AutoSize = true;
    		this.label16.ForeColor = System.Drawing.Color.FromArgb(38, 50, 56);
    		this.label16.Location = new System.Drawing.Point(40, 53);
    		this.label16.Name = "label16";
    		this.label16.Size = new System.Drawing.Size(118, 23);
    		this.label16.TabIndex = 0;
    		this.label16.Text = "Ma nhân viên:";
    		this.lblTitle.BackColor = System.Drawing.Color.FromArgb(25, 118, 210);
    		this.lblTitle.Dock = System.Windows.Forms.DockStyle.Top;
    		this.lblTitle.Font = new System.Drawing.Font("Segoe UI", 16f, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
    		this.lblTitle.ForeColor = System.Drawing.Color.White;
    		this.lblTitle.Location = new System.Drawing.Point(0, 0);
    		this.lblTitle.Name = "lblTitle";
    		this.lblTitle.Size = new System.Drawing.Size(1200, 50);
    		this.lblTitle.TabIndex = 0;
    		this.lblTitle.Text = "QUẢN LÝ Y TẾ - ĐIỀU PHỐI VIÊN";
    		this.lblTitle.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
    		base.AutoScaleDimensions = new System.Drawing.SizeF(8f, 20f);
    		base.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
    		this.BackColor = System.Drawing.Color.FromArgb(245, 247, 250);
    		base.ClientSize = new System.Drawing.Size(1200, 800);
    		base.Controls.Add(this.tabCoordinator);
    		base.Controls.Add(this.lblTitle);
    		base.Name = "frmCoordinator";
    		this.Text = "Quản lý Y Tế - Điều phối viên";
    		base.WindowState = System.Windows.Forms.FormWindowState.Maximized;
    		base.Load += new System.EventHandler(frmCoordinator_Load);
    		this.tabCoordinator.ResumeLayout(false);
    		this.tabPatients.ResumeLayout(false);
    		this.splitContainer1.Panel1.ResumeLayout(false);
    		this.splitContainer1.Panel2.ResumeLayout(false);
    		((System.ComponentModel.ISupportInitialize)this.splitContainer1).EndInit();
    		this.splitContainer1.ResumeLayout(false);
    		((System.ComponentModel.ISupportInitialize)this.dgvPatients).EndInit();
    		this.panel1.ResumeLayout(false);
    		this.panel1.PerformLayout();
    		this.grpPatientDetails.ResumeLayout(false);
    		this.grpPatientDetails.PerformLayout();
    		this.tabCreateMR.ResumeLayout(false);
    		this.grpCreateMR.ResumeLayout(false);
    		this.grpCreateMR.PerformLayout();
    		this.tabAssignDoctor.ResumeLayout(false);
    		this.splitContainer2.Panel1.ResumeLayout(false);
    		this.splitContainer2.Panel2.ResumeLayout(false);
    		((System.ComponentModel.ISupportInitialize)this.splitContainer2).EndInit();
    		this.splitContainer2.ResumeLayout(false);
    		((System.ComponentModel.ISupportInitialize)this.dgvMedicalRecords).EndInit();
    		this.groupBox1.ResumeLayout(false);
    		this.groupBox1.PerformLayout();
    		this.tabAssignTech.ResumeLayout(false);
    		this.splitContainer3.Panel1.ResumeLayout(false);
    		this.splitContainer3.Panel2.ResumeLayout(false);
    		((System.ComponentModel.ISupportInitialize)this.splitContainer3).EndInit();
    		this.splitContainer3.ResumeLayout(false);
    		((System.ComponentModel.ISupportInitialize)this.dgvServiceRecords).EndInit();
    		this.groupBox2.ResumeLayout(false);
    		this.groupBox2.PerformLayout();
    		this.tabProfile.ResumeLayout(false);
    		this.groupBox3.ResumeLayout(false);
    		this.groupBox3.PerformLayout();
    		base.ResumeLayout(false);
    }
}
}



