-- ==============================================================================
-- 02_standard_audit.sql
-- Chạy dưới quyền: sysdba
-- ==============================================================================
ALTER SESSION SET CONTAINER = PDB_QLYT;
ALTER SESSION SET CURRENT_SCHEMA = hospital;

-- B. Hủy các thiết lập quy tắc cũ
BEGIN EXECUTE IMMEDIATE 'NOAUDIT ALL ON hospital.staff'; EXCEPTION WHEN OTHERS THEN NULL; END;
BEGIN EXECUTE IMMEDIATE 'NOAUDIT ALL ON hospital.department'; EXCEPTION WHEN OTHERS THEN NULL; END;
BEGIN EXECUTE IMMEDIATE 'NOAUDIT ALL ON hospital.medical_record'; EXCEPTION WHEN OTHERS THEN NULL; END;
BEGIN EXECUTE IMMEDIATE 'NOAUDIT ALL ON hospital.USP_MANAGE_PRESCRIPTION'; EXCEPTION WHEN OTHERS THEN NULL; END;
BEGIN EXECUTE IMMEDIATE 'NOAUDIT ALL ON hospital.SP_COORD_GET_DOCTORS'; EXCEPTION WHEN OTHERS THEN NULL; END;

-- Tạo function để demo audit
CREATE OR REPLACE FUNCTION hospital_dba.F_GET_DOCTOR_STATS(p_dept_id IN VARCHAR2) 
RETURN NUMBER AS
    v_cnt NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_cnt FROM hospital.staff WHERE dept_id = p_dept_id;
    RETURN v_cnt;
END;
/   
GRANT EXECUTE ON hospital_dba.F_GET_DOCTOR_STATS TO rl_doctor, rl_coordinator;

-- NC#1: TABLE - Xóa nhân viên
AUDIT DELETE ON hospital.staff BY ACCESS WHENEVER SUCCESSFUL;
AUDIT DELETE ON hospital.staff BY ACCESS WHENEVER NOT SUCCESSFUL;

-- NC#2: TABLE - Cập nhật thông tin bệnh nhân
AUDIT UPDATE ON hospital.patient BY ACCESS WHENEVER SUCCESSFUL;
AUDIT UPDATE ON hospital.patient BY ACCESS WHENEVER NOT SUCCESSFUL;

-- NC#3: VIEW - Tra cứu danh sách bác sĩ
AUDIT SELECT ON hospital.VW_COORD_DOCTORS BY ACCESS WHENEVER SUCCESSFUL;
AUDIT SELECT ON hospital.VW_COORD_DOCTORS BY ACCESS WHENEVER NOT SUCCESSFUL;

-- NC#4: STORED PROCEDURE - Cập nhật HSBA
AUDIT EXECUTE ON hospital.USP_UPDATE_MEDICAL_RECORD BY ACCESS WHENEVER SUCCESSFUL;
AUDIT EXECUTE ON hospital.USP_UPDATE_MEDICAL_RECORD BY ACCESS WHENEVER NOT SUCCESSFUL;

-- NC#5: FUNCTION - Thống kê số bác sĩ theo khoa
AUDIT EXECUTE ON hospital_dba.F_GET_DOCTOR_STATS BY ACCESS WHENEVER SUCCESSFUL;
AUDIT EXECUTE ON hospital_dba.F_GET_DOCTOR_STATS BY ACCESS WHENEVER NOT SUCCESSFUL;
