-- ==============================================================================
-- 02_standard_audit.sql
-- Cháº¡y dÆ°á»›i quyá»n: sysdba
-- ==============================================================================
ALTER SESSION SET CONTAINER = PDB_QLYT;

-- B. Há»§y cÃ¡c thiáº¿t láº­p quy táº¯c cÅ©
BEGIN
    BEGIN EXECUTE IMMEDIATE 'NOAUDIT ALL ON hospital.staff'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'NOAUDIT ALL ON hospital.department'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'NOAUDIT ALL ON hospital.medical_record'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'NOAUDIT ALL ON hospital.USP_MANAGE_PRESCRIPTION'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'NOAUDIT ALL ON hospital.VW_COORD_DOCTORS'; EXCEPTION WHEN OTHERS THEN NULL; END;
END;
/

-- Táº¡o function Ä‘á»ƒ demo audit
CREATE OR REPLACE FUNCTION hospital_dba.F_GET_DOCTOR_STATS(p_dept_id IN VARCHAR2) 
RETURN NUMBER AS
    v_cnt NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_cnt FROM hospital.staff WHERE dept_id = p_dept_id;
    RETURN v_cnt;
END;
/   
GRANT EXECUTE ON hospital_dba.F_GET_DOCTOR_STATS TO rl_doctor, rl_coordinator;

-- NC#1: TABLE - XÃ³a nhÃ¢n viÃªn
AUDIT DELETE ON hospital.staff BY ACCESS WHENEVER SUCCESSFUL;
AUDIT DELETE ON hospital.staff BY ACCESS WHENEVER NOT SUCCESSFUL;

-- NC#2: TABLE - Cáº­p nháº­t thÃ´ng tin bá»‡nh nhÃ¢n
AUDIT UPDATE ON hospital.patient BY ACCESS WHENEVER SUCCESSFUL;
AUDIT UPDATE ON hospital.patient BY ACCESS WHENEVER NOT SUCCESSFUL;

-- NC#3: VIEW - Tra cá»©u danh sÃ¡ch bÃ¡c sÄ©
AUDIT SELECT ON hospital.VW_COORD_DOCTORS BY ACCESS WHENEVER SUCCESSFUL;
AUDIT SELECT ON hospital.VW_COORD_DOCTORS BY ACCESS WHENEVER NOT SUCCESSFUL;

-- NC#4: STORED PROCEDURE - Cáº­p nháº­t HSBA
AUDIT EXECUTE ON hospital.USP_UPDATE_MEDICAL_RECORD BY ACCESS WHENEVER SUCCESSFUL;
AUDIT EXECUTE ON hospital.USP_UPDATE_MEDICAL_RECORD BY ACCESS WHENEVER NOT SUCCESSFUL;

-- NC#5: FUNCTION - Thá»‘ng kÃª sá»‘ bÃ¡c sÄ© theo khoa
AUDIT EXECUTE ON hospital_dba.F_GET_DOCTOR_STATS BY ACCESS WHENEVER SUCCESSFUL;
AUDIT EXECUTE ON hospital_dba.F_GET_DOCTOR_STATS BY ACCESS WHENEVER NOT SUCCESSFUL;
