-- ==============================================================================
-- 03_audit_views.sql
-- Run as: sysdba
-- ==============================================================================
ALTER SESSION SET CONTAINER = PDB_QLYT;
ALTER SESSION SET CURRENT_SCHEMA = hospital_dba;

-- 4.1. Tab Kiểm toán hệ thống
CREATE OR REPLACE PROCEDURE hospital_dba.USP_GET_REQ32_LOGS (p_cursor OUT SYS_REFCURSOR) AS
BEGIN
    OPEN p_cursor FOR
    SELECT CAST(USERNAME AS VARCHAR2(128)) as USERNAME, TO_CHAR(TIMESTAMP, 'DD/MM/YYYY HH24:MI:SS') as TIMESTAMP, 
           CAST(OBJ_NAME AS VARCHAR2(128)) as OBJECT, CAST(ACTION_NAME AS VARCHAR2(128)) as ACTION, 
           CASE WHEN RETURNCODE = 0 THEN 'Success' ELSE 'Failed' END AS STATUS, DBMS_LOB.SUBSTR(SQL_TEXT, 4000, 1) as SQL_TEXT
    FROM DBA_AUDIT_TRAIL 
    WHERE OBJ_NAME IN ('STAFF', 'PATIENT', 'VW_COORD_DOCTORS', 'USP_UPDATE_MEDICAL_RECORD', 'F_GET_DOCTOR_STATS')
    ORDER BY TIMESTAMP DESC;
END;
/

-- 4.2. Tab Đơn thuốc
CREATE OR REPLACE PROCEDURE hospital_dba.USP_GET_REQ33A_LOGS (p_cursor OUT SYS_REFCURSOR) AS
BEGIN
    OPEN p_cursor FOR
    SELECT CAST(DB_USER AS VARCHAR2(128)) as USERNAME, TO_CHAR(TIMESTAMP, 'DD/MM/YYYY HH24:MI:SS') as TIMESTAMP, 
           CAST(OBJECT_NAME AS VARCHAR2(128)) as OBJECT, 'UPDATE' as ACTION, 'Success' AS STATUS, CAST(SQL_TEXT AS VARCHAR2(4000)) as SQL_TEXT
    FROM DBA_FGA_AUDIT_TRAIL WHERE POLICY_NAME = 'FGA_PRESCRIPTION_COLS'
    ORDER BY TIMESTAMP DESC;
END;
/

-- 4.3. Tab HSBA (Gộp FGA-Thành công và Unified-Thất bại)
CREATE OR REPLACE PROCEDURE hospital_dba.USP_GET_REQ33BC_LOGS (p_cursor OUT SYS_REFCURSOR) AS
BEGIN
    OPEN p_cursor FOR
    SELECT CAST(DB_USER AS VARCHAR2(128)) as USERNAME, TO_CHAR(TIMESTAMP, 'DD/MM/YYYY HH24:MI:SS') as TIMESTAMP, 
           CAST(OBJECT_NAME AS VARCHAR2(128)) as OBJECT, 'UPDATE' as ACTION, 'Success' AS STATUS, CAST(SQL_TEXT AS VARCHAR2(4000)) as SQL_TEXT
    FROM DBA_FGA_AUDIT_TRAIL WHERE POLICY_NAME = 'FGA_MEDICAL_RECORD_COLS'
    UNION ALL
    SELECT CAST(DBUSERNAME AS VARCHAR2(128)), TO_CHAR(EVENT_TIMESTAMP, 'DD/MM/YYYY HH24:MI:SS'), 
           CAST(OBJECT_NAME AS VARCHAR2(128)), 'UPDATE', 'Failed', DBMS_LOB.SUBSTR(SQL_TEXT, 4000, 1)
    FROM UNIFIED_AUDIT_TRAIL WHERE OBJECT_NAME = 'MEDICAL_RECORD' AND RETURN_CODE != 0
    ORDER BY TIMESTAMP DESC;
END;
/

-- 4.4. Tab Dịch vụ (Lấy từ Unified Thất bại)
CREATE OR REPLACE PROCEDURE hospital_dba.USP_GET_REQ33D_LOGS (p_cursor OUT SYS_REFCURSOR) AS
BEGIN
    OPEN p_cursor FOR
    SELECT CAST(DBUSERNAME AS VARCHAR2(128)) as USERNAME, TO_CHAR(EVENT_TIMESTAMP, 'DD/MM/YYYY HH24:MI:SS') as TIMESTAMP, 
           CAST(OBJECT_NAME AS VARCHAR2(128)) as OBJECT, CAST(ACTION_NAME AS VARCHAR2(128)) as ACTION, 
           'Failed' AS STATUS, DBMS_LOB.SUBSTR(SQL_TEXT, 4000, 1) as SQL_TEXT
    FROM UNIFIED_AUDIT_TRAIL WHERE OBJECT_NAME = 'SERVICE_RECORD' AND RETURN_CODE != 0
    ORDER BY EVENT_TIMESTAMP DESC;
END;
/
