-- Chạy bằng SYSDBA

BEGIN
    -- A. Xóa nhật ký (Logs)
    EXECUTE IMMEDIATE 'DELETE FROM SYS.AUD$';      -- Xóa Standard Audit log
    EXECUTE IMMEDIATE 'DELETE FROM SYS.FGA_LOG$';  -- Xóa Fine-Grained Audit log
    COMMIT;
    
    -- Xóa Unified Audit Trail (phải dùng API, không được DELETE trực tiếp)
    BEGIN
        DBMS_AUDIT_MGMT.FLUSH_UNIFIED_AUDIT_TRAIL;  -- Ép đẩy log từ RAM xuống disk
    EXCEPTION WHEN OTHERS THEN NULL; END;
    
    BEGIN
        -- use_last_arch_timestamp => FALSE: xóa toàn bộ, không cần đánh dấu timestamp
        DBMS_AUDIT_MGMT.CLEAN_AUDIT_TRAIL(
            audit_trail_type        => DBMS_AUDIT_MGMT.AUDIT_TRAIL_UNIFIED,
            use_last_arch_timestamp => FALSE
        );
    EXCEPTION WHEN OTHERS THEN NULL; END;
    
    -- B. Hủy các thiết lập quy tắc cũ
    BEGIN EXECUTE IMMEDIATE 'NOAUDIT ALL ON hospital_dba.medical_record'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'NOAUDIT ALL ON hospital_dba.staff'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'NOAUDIT ALL ON hospital_dba.V_PATIENT_SELF'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'NOAUDIT ALL ON hospital_dba.USP_MANAGE_PRESCRIPTION'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'NOAUDIT ALL ON hospital_dba.F_EXTRACT_MEDICAL_HISTORY'; EXCEPTION WHEN OTHERS THEN NULL; END;
    
    -- C. Xóa các Fine-Grained Audit Policies cũ
    BEGIN DBMS_FGA.DROP_POLICY('HOSPITAL_DBA', 'PRESCRIPTION', 'FGA_PRESCRIPTION_COLS');  EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN DBMS_FGA.DROP_POLICY('HOSPITAL_DBA', 'MEDICAL_RECORD', 'FGA_MEDICAL_RECORD_COLS'); EXCEPTION WHEN OTHERS THEN NULL; END;
    
    -- D. Xóa Unified Audit Policy cũ
    BEGIN EXECUTE IMMEDIATE 'NOAUDIT POLICY AUD_ILLEGAL_MEDICAL_RECORD_POLICY'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'DROP AUDIT POLICY AUD_ILLEGAL_MEDICAL_RECORD_POLICY';         EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'NOAUDIT POLICY AUD_ILLEGAL_SERVICE_RECORD_POLICY'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'DROP AUDIT POLICY AUD_ILLEGAL_SERVICE_RECORD_POLICY';         EXCEPTION WHEN OTHERS THEN NULL; END;
    
    -- E. Xóa các Stored Procedures cũ của Nhật ký
    BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE hospital_dba.USP_GET_STANDARD_AUDIT_LOGS'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE hospital_dba.USP_GET_PRESCRIPTION_AUDIT_LOGS';     EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE hospital_dba.USP_GET_MEDICAL_RECORD_AUDIT_LOGS';    EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE hospital_dba.USP_GET_SERVICE_RECORD_AUDIT_LOGS';     EXCEPTION WHEN OTHERS THEN NULL; END;
END;
/

