ALTER SESSION SET CONTAINER = PDB_QLYT;
CREATE OR REPLACE PROCEDURE hospital_dba.GET_TECHNICIAN_PERSONAL_INFO(
    P_CURSOR OUT SYS_REFCURSOR
)
AUTHID DEFINER
AS
BEGIN
    OPEN P_CURSOR FOR
        SELECT
            ST.STAFF_ID,
            ST.FULL_NAME,
            ST.GENDER,
            ST.BIRTHDATE,
            ST.ID_CARD,
            ST.STAFF_ROLE AS ROLE,
            ST.PHONE,
            ST.HOMETOWN,
            D.DEPT_NAME,
            ST.FACILITY
        FROM HOSPITAL.STAFF ST
        LEFT JOIN HOSPITAL.DEPARTMENT D ON ST.DEPT_ID = D.DEPT_ID
        WHERE UPPER(ST.USERNAME_DB) = SYS_CONTEXT('USERENV', 'SESSION_USER')
          AND (ST.STAFF_ROLE LIKE N'K%thu%t vi%n' OR ST.STAFF_ROLE = N'Kỹ thuật viên')
          AND ST.IS_ACTIVE = 1;
END;
/
GRANT EXECUTE ON hospital_dba.GET_TECHNICIAN_PERSONAL_INFO TO RL_TECHNICIAN;
EXIT;
