-- ==============================================================================
-- 02_technician_procedures.sql
-- Run as: hospital
-- ==============================================================================

ALTER SESSION SET CONTAINER = PDB_QLYT;
ALTER SESSION SET CURRENT_SCHEMA = hospital;

CREATE OR REPLACE PROCEDURE GET_TECHNICIAN_SERVICE_RECORDS (
    P_CURSOR OUT SYS_REFCURSOR
)
AUTHID CURRENT_USER
AS
BEGIN
    OPEN P_CURSOR FOR
        SELECT
            SR.RECORD_ID,
            SR.SERVICE_TYPE,
            SR.SERVICE_DATE,
            SR.TECHNICIAN_ID,
            SR.SERVICE_RESULT
        FROM hospital.V_TECHNICIAN_SERVICE_RECORD SR
        ORDER BY SR.SERVICE_DATE DESC;
END;
/

CREATE OR REPLACE PROCEDURE UPDATE_TECHNICIAN_SERVICE_RESULT (
    P_RECORD_ID      IN VARCHAR2,
    P_SERVICE_TYPE   IN NVARCHAR2,
    P_SERVICE_DATE   IN DATE,
    P_SERVICE_RESULT IN NVARCHAR2
)
AUTHID CURRENT_USER
AS
    V_ROWS_UPDATED NUMBER;
BEGIN
    UPDATE hospital.SERVICE_RECORD SR
    SET SR.SERVICE_RESULT = P_SERVICE_RESULT
    WHERE SR.RECORD_ID = P_RECORD_ID
      AND SR.SERVICE_TYPE = P_SERVICE_TYPE
      AND TRUNC(SR.SERVICE_DATE) = TRUNC(P_SERVICE_DATE)
      AND EXISTS (
          SELECT 1 
          FROM hospital.V_TECHNICIAN_SERVICE_RECORD VSR 
          WHERE VSR.RECORD_ID = SR.RECORD_ID 
            AND VSR.SERVICE_TYPE = SR.SERVICE_TYPE 
            AND TRUNC(VSR.SERVICE_DATE) = TRUNC(SR.SERVICE_DATE)
      );
    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE GET_TECHNICIAN_PERSONAL_INFO (
    P_CURSOR OUT SYS_REFCURSOR
)
AUTHID CURRENT_USER
AS
BEGIN
    OPEN P_CURSOR FOR
        SELECT ST.STAFF_ID, ST.FULL_NAME, ST.GENDER, ST.BIRTHDATE, ST.ID_CARD, 
               ST.HOMETOWN, ST.PHONE, D.DEPT_NAME, ST.FACILITY, ST.STAFF_ROLE AS ROLE
        FROM hospital.STAFF ST
        LEFT JOIN hospital.DEPARTMENT D ON ST.DEPT_ID = D.DEPT_ID
        WHERE UPPER(ST.USERNAME_DB) = SYS_CONTEXT('USERENV', 'SESSION_USER');
END;
/

CREATE OR REPLACE PROCEDURE UPDATE_TECHNICIAN_PERSONAL_INFO (
    P_HOMETOWN IN NVARCHAR2,
    P_PHONE    IN VARCHAR2
)
AUTHID CURRENT_USER
AS
BEGIN
    UPDATE hospital.STAFF
    SET HOMETOWN = P_HOMETOWN,
        PHONE = P_PHONE
    WHERE UPPER(USERNAME_DB) = SYS_CONTEXT('USERENV', 'SESSION_USER');
    COMMIT;
END;
/
